# Generated by Django 5.1.4 on 2026-05-14 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text="Уникальный адрес страницы, например 'about' для /about/", max_length=255, unique=True, verbose_name='URL-адрес (slug)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, help_text='Снимите галочку, чтобы временно скрыть блок без удаления', verbose_name='Виден на сайте')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='blocks.block', verbose_name='Блок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='pages.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок на странице',
                'verbose_name_plural': 'Блоки на странице',
                'ordering': ['position', 'id'],
                'unique_together': {('page', 'block')},
            },
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pages', to='pages.page', verbose_name='Страница')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ редактора к странице',
                'verbose_name_plural': 'Доступы редакторов к страницам',
                'unique_together': {('user', 'page')},
            },
        ),
    ]
