# Generated by Django 5.1.4 on 2026-05-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPage',
        ),
    ]
