# Generated by Django 5.1.4 on 2026-05-14 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/', verbose_name='Изображение')),
                ('tags', models.CharField(blank=True, help_text='Через запятую, например: важно, новости, ИУ-5', max_length=255, verbose_name='Теги')),
                ('is_urgent', models.BooleanField(default=False, help_text='Срочные публикации выделяются в ленте', verbose_name='Срочная публикация')),
                ('published_at', models.DateTimeField(blank=True, help_text='Если не указана, используется дата создания', null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('news_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blocks.newsfeed', verbose_name='Новостная лента')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-is_urgent', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_post_publish_091963_idx'), models.Index(fields=['news_feed', '-published_at'], name='news_post_news_fe_414c90_idx')],
            },
        ),
    ]
