# Generated by Django 5.1.4 on 2026-05-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Важные публикации выделяются в ленте', verbose_name='Важная публикация'),
        ),
    ]
