# Generated by Django 5.1.4 on 2026-05-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(blank=True, help_text='Заполните, если ссылка ведёт на внешний ресурс', verbose_name='Внешний URL')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок пункта меню')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Виден на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='blocks.headerlinksblock', verbose_name='Блок меню')),
                ('target_page', models.ForeignKey(blank=True, help_text='Если задана — ссылка ведёт на внутреннюю страницу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_links', to='pages.page', verbose_name='Целевая страница системы')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['position', 'id'],
            },
        ),
    ]
