# Generated by Django 5.1.4 on 2026-05-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(editable=False, help_text='Технический идентификатор типа блока', max_length=32, verbose_name='Тип блока')),
                ('admin_label', models.CharField(blank=True, help_text='Подпись блока в списке для удобства администратора', max_length=128, verbose_name='Название для админки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки (все типы)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaqBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блока')),
            ],
            options={
                'verbose_name': 'FAQ-блок',
                'verbose_name_plural': 'FAQ-блоки',
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='FooterContactsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('weekends', models.CharField(blank=True, help_text='Например: «Сб, Вс»', max_length=128, verbose_name='Выходные дни')),
                ('vk_url', models.URLField(blank=True, verbose_name='Ссылка ВКонтакте')),
                ('tg_url', models.URLField(blank=True, verbose_name='Ссылка Telegram')),
                ('max_url', models.URLField(blank=True, verbose_name='Ссылка Max')),
            ],
            options={
                'verbose_name': 'Контакты (подвал)',
                'verbose_name_plural': 'Контакты (подвал)',
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='HeaderLinksBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
            ],
            options={
                'verbose_name': 'Меню (шапка)',
                'verbose_name_plural': 'Меню (шапка)',
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='HtmlBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('html_content', models.TextField(help_text='Произвольный HTML-код, который будет вставлен на страницу', verbose_name='HTML-содержимое')),
            ],
            options={
                'verbose_name': 'HTML-блок',
                'verbose_name_plural': 'HTML-блоки',
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок ленты')),
            ],
            options={
                'verbose_name': 'Новостная лента',
                'verbose_name_plural': 'Новостные ленты',
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('faq_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='blocks.faqblock', verbose_name='FAQ-блок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['position', 'id'],
            },
        ),
    ]
