# Generated by Django 5.1.4 on 2026-05-15 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Пользователи с ролью «Редактор», которым разрешено публиковать посты в этой ленте', related_name='news_feeds', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы ленты'),
        ),
    ]
