# Generated by Django 5.1.4 on 2026-05-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_newsfeed_editors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelEmbedBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('table_url', models.URLField(help_text='Вставьте публичную ссылку или embed-код таблицы (Google Sheets, Office Online)', verbose_name='Ссылка на таблицу')),
            ],
            options={
                'verbose_name': 'Excel-таблица',
                'verbose_name_plural': 'Excel-таблицы',
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='GoogleDocBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('doc_url', models.URLField(help_text='Вставьте публичную ссылку или embed-код Google Docs', verbose_name='Ссылка на Google Документ')),
            ],
            options={
                'verbose_name': 'Google Документ',
                'verbose_name_plural': 'Google Документы',
            },
            bases=('blocks.block',),
        ),
        migrations.AlterField(
            model_name='block',
            name='admin_label',
            field=models.CharField(blank=True, help_text='Подпись блока в списке для удобства администратора', max_length=128, verbose_name='Название в системе'),
        ),
    ]
