# Generated by Django 5.1.4 on 2026-05-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_excelembedblock_googledocblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('table_url', models.URLField(help_text='Вставьте публичную ссылку или embed-код таблицы', verbose_name='Ссылка на Google Таблицу')),
            ],
            options={
                'verbose_name': 'Блок Google таблицы',
                'verbose_name_plural': 'Блоки Google таблиц',
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='LinksBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('title', models.CharField(max_length=255, verbose_name='Название блока с ссылками')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link1', models.URLField(verbose_name='Ссылка №1')),
                ('link1_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание ссылки №1')),
                ('link2', models.URLField(blank=True, null=True, verbose_name='Ссылка №2')),
                ('link2_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание ссылки №2')),
                ('link3', models.URLField(blank=True, null=True, verbose_name='Ссылка №3')),
                ('link3_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание ссылки №3')),
                ('link4', models.URLField(blank=True, null=True, verbose_name='Ссылка №4')),
                ('link4_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание ссылки №4')),
                ('link5', models.URLField(blank=True, null=True, verbose_name='Ссылка №5')),
                ('link5_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание ссылки №5')),
                ('link6', models.URLField(blank=True, null=True, verbose_name='Ссылка №6')),
                ('link6_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание ссылки №6')),
            ],
            options={
                'verbose_name': 'Блок ссылок',
                'verbose_name_plural': 'Блоки ссылок',
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='VkVideoBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.block')),
                ('video_url', models.URLField(help_text='Публичная ссылка на видео VK', verbose_name='Ссылка на VK видео')),
            ],
            options={
                'verbose_name': 'Блок VK видео',
                'verbose_name_plural': 'Блоки VK видео',
            },
            bases=('blocks.block',),
        ),
        migrations.AlterModelOptions(
            name='googledocblock',
            options={'verbose_name': 'Блок Google документа', 'verbose_name_plural': 'Блоки Google документов'},
        ),
        migrations.DeleteModel(
            name='ExcelEmbedBlock',
        ),
    ]
